import type { ProcessorDefects, ProcessorEquipment, ProcessorUniversalNames } from "@/entities/ITEMS/processor-item/types/processor-item.types"

export const PROCESSOR_MODES: ProcessorUniversalNames[] = [
    "Core i3/5-пок",
    "Core i3/6-пок",
    "Core i3/7-пок",
    "Core i3/8-пок",
    "Core i3/9-пок",
    "Core i3/10-пок",
    "Core i3/11-пок",
    "Core i3/12-пок",
    "Core i3/13-пок",
    "Core i5/5 пок",
    "Core i5/6 пок",
    "Core i5/7 пок",
    "Core i5/8 пок",
    "Core i5/9 пок",
    "Core i5/10 пок",
    "Core i5/11 пок",
    "Core i5/12 пок",
    "Core i5/13 пок",
    "Core i7/5 пок",
    "Core i7/6 пок",
    "Core i7/7 пок",
    "Core i7/8 пок",
    "Core i7/9 пок",
    "Core i7/10 пок",
    "Core i7/11 пок",
    "Core i7/12 пок",
    "Core i7/13 пок",
    "Core i9/5 пок",
    "Core i9/6 пок",
    "Core i9/7 пок",
    "Core i9/8 пок",
    "Core i9/9 пок",
    "Core i9/10 пок",
    "Core i9/11 пок",
    "Core i9/12 пок",
    "Core i9/13 пок",
    "Ryzen 3 (4-е поколение) 2020-2022 (4 ядер / 8 потоков)",
    "Ryzen 3 (5-е поколение) 2023-2024 (4 ядер / 8 потоков)",
    "Ryzen 5 (4-е поколение) 2020-2022 (6 ядер / 12 потоков)",
    "Ryzen 5 (5-е поколение) 2023 (6 ядер / 12 потоков)",
    "Ryzen 7 (1-е поколение) 2017 (8 ядер / 16 потоков)",
    "Ryzen 7 (2-е поколение) 2018 (8 ядер / 16 потоков)",
    "Ryzen 7 (3-е поколение) 2019 (8 ядер / 16 потоков)",
    "Ryzen 7 (4-е поколение) 2020-2022 (8 ядер / 16 потоков)",
    "Ryzen 7 (5-е поколение) 2023 (8 ядер / 16 потоков)",
    "Ryzen 9 (1-е поколение) 2019 (12 ядер / 24 потоков)",
    "Ryzen 9 (2-е поколение) 2020 (12 ядер / 24 потоков)",
    "Ryzen 9 (3-е поколение) 2022-2023 (12 ядер / 24 потоков)",
    "Ryzen 9 (4-е поколение) 2023 (12 ядер / 24 потоков)",
    "Threadripper (1-е поколение) 2017 (8 ядер / 16 потоков)",
    "Threadripper (2-е поколение) 2018 (12 ядер / 24 потоков)",
    "Threadripper (3-е поколение) 2019 (24 ядер / 48 потоков)",
    "Threadripper (4-е поколение) 2023 (24 ядер / 48 потоков)"
]

export const PROCESSOR_EQUIPMENT_TITLE: Record<keyof ProcessorEquipment, string> = {
    originalBox: "Оригинальная коробка (есть / нету)",
    mouse: "Мышь (есть / нету)",
    documents: "Документы (есть / нету)",
    bag: "Сумка (есть / нету)",
    oldDesign: "Старый дизайн (да / нет)",
    chargerOriginal: "Оригинальное зарядное устройство (да / нет)",
    chargerNotOriginal: "Неоригинальное зарядное устройство (да / нет)",
    chargerNot: "Зарядное устройство отсутствует (да / нет)"
}

export const PROCESSOR_DEFECTS_TITLE: Record<keyof ProcessorDefects, string> = {
    videoCardWithIcon: "Видеокарта со значком (да / нет)",
    crackLowerPart: "Трещина в нижней части (есть / нету)",
    "crackTopPart(whereKeyboard)": "Трещина в верхней части (где клавиатура) (есть / нету)",
    crackScreenFrame: "Трещина в рамке экрана (есть / нету)",
    "crackOuter(displayCover)": "Трещина наружняя (Крышка дисплея) (есть / нету)",
    mountingBolts: "Нет болтиков крепления (есть / нету)",
    smallScratches: "Мелкие царапины (есть / нету)",
    strongScratches: "Сильные царапины (есть / нету)",
    "displayCoverDoesntStay(45Degrees)": "Крышка дисплея не держится (при 45градусов) (да / нет)",
    "openingCase(partKeyboardMonitor)RisesDoesntHold": "При открывании приподнимается корпус (часть клавиатуры или монитора) или Вообще не держит (да / нет)",
    "noKeys(1 to 10 pcs)": "Нет клавиш (от 1-10шт) (да, нет клавиш / нет, есть клавиши)",
    wornLettersKeyboard: "Потертые буквы на клавиатуре (да / нет)",
    someKeysDontWork: "Не работают некоторые из клавиш (да / нет)",
    keysDontWork: "Не работает клавиатура вообще (да / нет)",
    touchPadDontWork: "Не работает TouchPad (да / нет)",
    "needHoldPressDown(chargeFlows)": "Нужно придерживать, придавливать (чтоб шел заряд) (да / нет)",
    dontCharge: "Не заряжает вообще (да / нет)",
    stopsChargingCoupleMinutes: "Перестает заряжать через пару минут (да / нет)",
    worksNetwork: "Работает от сети (да / нет)",
    crackDisplay: "Трещина на дисплее (есть / нету)",
    colorStripes: "Цветные полоски (есть / нету)",
    colorPoints: "Черные или белые точки, пятна (есть / нету)",
    flickeringBlinkingScreen: "Мерцание, моргание экрана (есть / нету)",
    coolerNoisy: "Шумит кулер (да / нет)",
    driveNoisy: "Шумит дисковод (да / нет)",
    driveBroken: "Сломан Дисковод (да / нет)",
    turnsOffItself: "Сам по себе отключается (экран или сам ноутбук) (да / нет)",
    doesntWorkWifi: "Wi-fi не работает? (да / нет)",
    dynamicDoesntWork: "Динамик не работает (да / нет)"
}

export const PROCESSOR_EQUIPMENT_CHECKED: Record<keyof ProcessorEquipment, boolean> = {
    originalBox: false,
    mouse: false,
    documents: false,
    bag: false,
    oldDesign: false,
    chargerOriginal: false,
    chargerNotOriginal: false,
    chargerNot: false
}

export const PROCESSOR_DEFECTS_CHECKED: Record<keyof ProcessorDefects, boolean> = {
    videoCardWithIcon: false,
    crackLowerPart: false,
    "crackTopPart(whereKeyboard)": false,
    crackScreenFrame: false,
    "crackOuter(displayCover)": false,
    mountingBolts: false,
    smallScratches: false,
    strongScratches: false,
    "displayCoverDoesntStay(45Degrees)": false,
    "openingCase(partKeyboardMonitor)RisesDoesntHold": false,
    "noKeys(1 to 10 pcs)": false,
    wornLettersKeyboard: false,
    someKeysDontWork: false,
    keysDontWork: false,
    touchPadDontWork: false,
    "needHoldPressDown(chargeFlows)": false,
    dontCharge: false,
    stopsChargingCoupleMinutes: false,
    worksNetwork: false,
    crackDisplay: false,
    colorStripes: false,
    colorPoints: false,
    flickeringBlinkingScreen: false,
    coolerNoisy: false,
    driveNoisy: false,
    driveBroken: false,
    turnsOffItself: false,
    doesntWorkWifi: false,
    dynamicDoesntWork: false
}