export type TVNames =
    | ""
    | "Haier LE {диагональ} K5500T"
    | "Haier LE {диагональ} K6500SA"
    | "Haier LE {диагональ} K6500U"
    | "Haier LE {диагональ} Q6500U"
    | "LG {диагональ} ET961H"
    | "LG {диагональ} LB652V"
    | "LG {диагональ} LB658V"
    | "LG {диагональ} LB673V"
    | "LG {диагональ} LF590V"
    | "LG {диагональ} LF652V"
    | "LG {диагональ} LH595V"
    | "LG {диагональ} LJ480U"
    | "LG {диагональ} LJ540V"
    | "LG {диагональ} LJ594U"
    | "LG {диагональ} LJ600U"
    | "LG {диагональ} LJ610V"
    | "LG {диагональ} LJ622V"
    | "LG {диагональ} LK480U"
    | "LG {диагональ} LK540B"
    | "LG {диагональ} LK5910"
    | "LG {диагональ} LK5990"
    | "LG {диагональ} LK6000"
    | "LG {диагональ} LK6100"
    | "LG {диагональ} LK610B"
    | "LG {диагональ} LK615B"
    | "LG {диагональ} LK6190"
    | "LG {диагональ} LK6200"
    | "LG {диагональ} LM5700"
    | "LG {диагональ} LM570B"
    | "LG {диагональ} LM6300"
    | "LG {диагональ} LM630B"
    | "LG {диагональ} LM6350"
    | "LG {диагональ} LM6390"
    | "LG {диагональ} LM6500"
    | "LG {диагональ} LN515S"
    | "LG {диагональ} LT340C"
    | "LG {диагональ} UN7400"
    | "LG {диагональ} LT661H"
    | "LG {диагональ} LV640S"
    | "LG {диагональ} LV761H"
    | "LG {диагональ} MT49S"
    | "LG {диагональ} MT93V"
    | "LG {диагональ} NANO79"
    | "LG {диагональ} NANO80"
    | "LG {диагональ} NANO81"
    | "LG {диагональ} NANO86"
    | "LG {диагональ} NANO90"
    | "LG {диагональ} NANO91"
    | "LG {диагональ} NANO95"
    | "LG {диагональ} NANO97"
    | "LG {диагональ} NANO99"
    | "LG {диагональ} SJ810V"
    | "LG {диагональ} SJ930V"
    | "LG {диагональ} SJ950V"
    | "LG {диагональ} SJ955V"
    | "LG {диагональ} SK7900"
    | "LG {диагональ} SK8000"
    | "LG {диагональ} SK8100"
    | "LG {диагональ} SK8500"
    | "LG {диагональ} SK9500"
    | "LG {диагональ} SM8000"
    | "LG {диагональ} SM8050"
    | "LG {диагональ} SM8200"
    | "LG {диагональ} SM8500"
    | "LG {диагональ} SM8600"
    | "LG {диагональ} SM8610"
    | "LG {диагональ} SM9000"
    | "LG {диагональ} SM9010"
    | "LG {диагональ} SM9800"
    | "LG {диагональ} SM9900"
    | "LG {диагональ} TL510S"
    | "LG {диагональ} TL520S"
    | "LG {диагональ} TN515S"
    | "LG {диагональ} TN520S"
    | "LG {диагональ} TN525S"
    | "LG {диагональ} UB980V"
    | "LG {диагональ} UC9V"
    | "LG {диагональ} UH603V"
    | "LG {диагональ} UH671V"
    | "LG {диагональ} UH770V"
    | "LG {диагональ} UJ620V"
    | "LG {диагональ} UJ630V"
    | "LG {диагональ} UJ631V"
    | "LG {диагональ} UJ634V"
    | "LG {диагональ} UJ639V"
    | "LG {диагональ} UJ651V"
    | "LG {диагональ} UJ655V"
    | "LG {диагональ} UJ670V"
    | "LG {диагональ} UJ675V"
    | "LG {диагональ} UJ740V"
    | "LG {диагональ} UJ750V"
    | "LG {диагональ} UK6100"
    | "LG {диагональ} UK6200"
    | "LG {диагональ} UK6300"
    | "LG {диагональ} UK6390"
    | "LG {диагональ} UK6450"
    | "LG {диагональ} UK6470"
    | "LG {диагональ} UK6500"
    | "LG {диагональ} UK6510"
    | "LG {диагональ} UK6550"
    | "LG {диагональ} UK6710"
    | "LG {диагональ} UK6750"
    | "LG {диагональ} UK7500"
    | "LG {диагональ} UK7550"
    | "LG {диагональ} UM7020"
    | "LG {диагональ} UM7090"
    | "LG {диагональ} UM7100"
    | "LG {диагональ} UM7110"
    | "LG {диагональ} UM7300"
    | "LG {диагональ} UM7400"
    | "LG {диагональ} UM7450"
    | "LG {диагональ} UM7490"
    | "LG {диагональ} UM7500"
    | "LG {диагональ} UM7510"
    | "LG {диагональ} UM7600"
    | "LG {диагональ} UM7610"
    | "LG {диагональ} UM7650"
    | "LG {диагональ} UM7660"
    | "LG {диагональ} UN"
    | "LG {диагональ} UN7000"
    | "LG {диагональ} UN7100"
    | "LG {диагональ} UN7300"
    | "LG {диагональ} UN7350"
    | "LG {диагональ} UN7390"
    | "LG {диагональ} LN510S"
    | "LG {диагональ} UN8000"
    | "LG {диагональ} UN8100"
    | "LG {диагональ} UN8500"
    | "LG {диагональ} US662H"
    | "LG {диагональ} UT640S"
    | "LG {диагональ} UT661H"
    | "LG {диагональ} UT665H"
    | "LG {диагональ} UU661H"
    | "LG OLED {диагональ} B6V"
    | "LG OLED {диагональ} B7V"
    | "LG OLED {диагональ} B8"
    | "LG OLED {диагональ} B8S"
    | "LG OLED {диагональ} B9"
    | "LG OLED {диагональ} BX"
    | "LG OLED {диагональ} C7V"
    | "LG OLED {диагональ} C8"
    | "LG OLED {диагональ} C9"
    | "LG OLED {диагональ} CX"
    | "LG OLED {диагональ} E7N"
    | "LG OLED {диагональ} E7V"
    | "LG OLED {диагональ} E8"
    | "LG OLED {диагональ} E9"
    | "LG OLED {диагональ} G6V"
    | "LG OLED {диагональ} G7V"
    | "LG OLED {диагональ} GX"
    | "LG OLED {диагональ} W7V"
    | "LG OLED {диагональ} W8"
    | "LG OLED {диагональ} W9"
    | "LG OLED {диагональ} WX"
    | "LG OLED {диагональ} Z9"
    | "LG OLED {диагональ} ZX"
    | "Panasonic TX {диагональ} CZR950"
    | "Panasonic TX {диагональ} ESR500"
    | "Panasonic TX {диагональ} EXR600"
    | "Panasonic TX {диагональ} EXR700"
    | "Panasonic TX {диагональ} EZR950"
    | "Panasonic TX {диагональ} FSR400"
    | "Panasonic TX {диагональ} FSR500"
    | "Panasonic TX {диагональ} FXR600"
    | "Panasonic TX {диагональ} FXR610"
    | "Panasonic TX {диагональ} FXR740"
    | "Panasonic TX {диагональ} GXR700"
    | "Panasonic TX {диагональ} GXR900"
    | "Panasonic TX {диагональ} GZR1000"
    | "Panasonic TX {диагональ} GZR950"
    | "Panasonic TX {диагональ} HSR400"
    | "Panasonic TX {диагональ} HXR900"
    | "Panasonic TX {диагональ} HXR940"
    | "Panasonic TX {диагональ} HZR1000"
    | "Philips {диагональ} OLED754"
    | "Philips {диагональ} PFS5302"
    | "Philips {диагональ} PFS5813"
    | "Philips {диагональ} PFS6825"
    | "Philips {диагональ} PFS8109"
    | "Philips {диагональ} PFS8159"
    | "Philips {диагональ} PFT5300"
    | "Philips {диагональ} PFT5301"
    | "Philips {диагональ} PFT6559"
    | "Philips {диагональ} PHS5302"
    | "Philips {диагональ} PHS6825"
    | "Philips {диагональ} PUS6262"
    | "Philips {диагональ} PUS6503"
    | "Philips {диагональ} PUS6504"
    | "Philips {диагональ} PUS6523"
    | "Philips {диагональ} PUS6654"
    | "Philips {диагональ} PUS6703"
    | "Philips {диагональ} PUS6704"
    | "Philips {диагональ} PUS6754"
    | "Philips {диагональ} PUS6774"
    | "Philips {диагональ} PUS7505"
    | "Philips {диагональ} PUS7555"
    | "Philips {диагональ} PUS7605"
    | "Philips {диагональ} PUS7805"
    | "Philips {диагональ} PUS7809"
    | "Philips {диагональ} PUS7855"
    | "Philips {диагональ} PUT6101"
    | "Philips {диагональ} PUT6162"
    | "Samsung HG {диагональ} EE590"
    | "Samsung HG {диагональ} EE690"
    | "Samsung HG {диагональ} EE890"
    | "Samsung HG {диагональ} EJ690"
    | "Samsung LH {диагональ} BETH"
    | "Samsung LV {диагональ} F390S"
    | "Samsung QE {диагональ} Q60R"
    | "Samsung QE {диагональ} Q60TA"
    | "Samsung QE {диагональ} Q64R"
    | "Samsung QE {диагональ} Q67R"
    | "Samsung QE {диагональ} Q67TA"
    | "Samsung QE {диагональ} Q6FAM"
    | "Samsung QE {диагональ} Q6FNA"
    | "Samsung QE {диагональ} Q700TA"
    | "Samsung QE {диагональ} Q70R"
    | "Samsung QE {диагональ} Q70TA"
    | "Samsung QE {диагональ} Q77R"
    | "Samsung QE {диагональ} Q77TA"
    | "Samsung QE {диагональ} Q7CAM"
    | "Samsung QE {диагональ} Q7FAM"
    | "Samsung QE {диагональ} Q7FNA"
    | "Samsung QE {диагональ} Q800TA"
    | "Samsung QE {диагональ} Q80R"
    | "Samsung QE {диагональ} Q80TA"
    | "Samsung QE {диагональ} Q85R"
    | "Samsung QE {диагональ} Q87TA"
    | "Samsung QE {диагональ} Q8CAM"
    | "Samsung QE {диагональ} Q8CNA"
    | "Samsung QE {диагональ} Q8FNA"
    | "Samsung QE {диагональ} Q900RA"
    | "Samsung QE {диагональ} Q900RB"
    | "Samsung QE {диагональ} Q900TS"
    | "Samsung QE {диагональ} Q90RA"
    | "Samsung QE {диагональ} Q90TA"
    | "Samsung QE {диагональ} Q950RB"
    | "Samsung QE {диагональ} Q950TS"
    | "Samsung QE {диагональ} Q95TA"
    | "Samsung QE {диагональ} Q9FAM"
    | "Samsung QE {диагональ} Q9FNA"
    | "Samsung TheFrameQE {диагональ} LS03RA"
    | "Samsung TheFrameQE {диагональ} LS03TA"
    | "Samsung TheFrameQE {диагональ} LS03TB"
    | "Samsung TheSerifQE {диагональ} LS01R"
    | "Samsung TheSerifQE {диагональ} LS01T"
    | "Samsung TheSeroQE {диагональ} LS05TA"
    | "Samsung UA {диагональ} N5500"
    | "Samsung UA {диагональ} RU7300"
    | "Samsung UE {диагональ} F5400"
    | "Samsung UE {диагональ} F6400"
    | "Samsung UE {диагональ} H5600"
    | "Samsung UE {диагональ} H5610"
    |  "Samsung UE {диагональ} H6200"
    | "Samsung UE {диагональ} H6240"
    | "Samsung UE {диагональ} H6410"
    | "Samsung UE {диагональ} H7000"
    | "Samsung UE {диагональ} HU7000"
    | "Samsung UE {диагональ} HU7200"
    | "Samsung UE {диагональ} HU8500T"
    | "Samsung UE {диагональ} HU9000"
    | "Samsung UE {диагональ} J4500"
    | "Samsung UE {диагональ} J4710"
    | "Samsung UE {диагональ} J5200"
    | "Samsung UE {диагональ} J5202"
    | "Samsung UE {диагональ} J5205"
    | "Samsung UE {диагональ} J6200"
    | "Samsung UE {диагональ} J6300"
    | "Samsung UE {диагональ} JS8500"
    | "Samsung UE {диагональ} JS9000"
    | "Samsung UE {диагональ} JS9500"
    | "Samsung UE {диагональ} JU6000"
    | "Samsung UE {диагональ} JU6400"
    | "Samsung UE {диагональ} JU6490"
    | "Samsung UE {диагональ} JU6600"
    | "Samsung UE {диагональ} JU6790"
    | "Samsung UE {диагональ} JU7000"
    | "Samsung UE {диагональ} JU7500"
    | "Samsung UE {диагональ} K5500"
    | "Samsung UE {диагональ} K5510"
    | "Samsung UE {диагональ} K5550"
    | "Samsung UE {диагональ} K6550"
    | "Samsung UE {диагональ} KS7000"
    | "Samsung UE {диагональ} KS7500"
    | "Samsung UE {диагональ} KS8000"
    | "Samsung UE {диагональ} KS9000"
    | "Samsung UE {диагональ} KU6000"
    | "Samsung UE {диагональ} KU6300"
    | "Samsung UE {диагональ} KU6450"
    | "Samsung UE {диагональ} KU6470"
    | "Samsung UE {диагональ} KU6500"
    | "Samsung UE {диагональ} KU6510"
    | "Samsung UE {диагональ} KU6650"
    | "Samsung UE {диагональ} KU6670"
    | "Samsung UE {диагональ} LS003"
    | "Samsung UE {диагональ} LS03N"
    | "Samsung UE {диагональ} M5500"
    | "Samsung UE {диагональ} M5503"
    | "Samsung UE {диагональ} M5510"
    | "Samsung UE {диагональ} M5513"
    | "Samsung UE {диагональ} M5550"
    | "Samsung UE {диагональ} M6500"
    | "Samsung UE {диагональ} M6550"
    | "Samsung UE {диагональ} MU6100"
    | "Samsung UE {диагональ} MU6103"
    | "Samsung UE {диагональ} MU6300"
    | "Samsung UE {диагональ} MU6303"
    | "Samsung UE {диагональ} MU6400"
    | "Samsung UE {диагональ} MU6450"
    | "Samsung UE {диагональ} MU6470"
    | "Samsung UE {диагональ} MU6500"
    | "Samsung UE {диагональ} MU6650"
    | "Samsung UE {диагональ} MU6670"
    | "Samsung UE {диагональ} MU7000"
    | "Samsung UE {диагональ} MU7500"
    | "Samsung UE {диагональ} MU8000"
    | "Samsung UE {диагональ} MU9000"
    | "Samsung UE {диагональ} N4500"
    | "Samsung UE {диагональ} N4510"
    | "Samsung UE {диагональ} N5300"
    | "Samsung UE {диагональ} N5510"
    | "Samsung UE {диагональ} N5540"
    | "Samsung UE {диагональ} N5570"
    | "Samsung UE {диагональ} NU7002"
    | "Samsung UE {диагональ} NU7090"
    | "Samsung UE {диагональ} NU7097"
    | "Samsung UE {диагональ} NU7100"
    | "Samsung UE {диагональ} NU7120"
    | "Samsung UE {диагональ} NU7140"
    | "Samsung UE {диагональ} NU7170"
    | "Samsung UE {диагональ} NU7300"
    | "Samsung UE {диагональ} NU7400"
    | "Samsung UE {диагональ} NU7450"
    | "Samsung UE {диагональ} NU7470"
    | "Samsung UE {диагональ} NU7500"
    | "Samsung UE {диагональ} NU7650"
    | "Samsung UE {диагональ} NU7670"
    | "Samsung UE {диагональ} NU8000"
    | "Samsung UE {диагональ} NU8070"
    | "Samsung UE {диагональ} NU8500"
    | "Samsung UE {диагональ} RU7097"
    | "Samsung UE {диагональ} RU7100"
    | "Samsung UE {диагональ} RU7120"
    | "Samsung UE {диагональ} RU7140"
    | "Samsung UE {диагональ} RU7170"
    | "Samsung UE {диагональ} RU7200"
    | "Samsung UE {диагональ} RU7300"
    | "Samsung UE {диагональ} RU7400"
    | "Samsung UE {диагональ} RU7410"
    | "Samsung UE {диагональ} RU7470"
    | "Samsung UE {диагональ} RU8000"
    | "Samsung UE {диагональ} S9"
    | "Samsung UE {диагональ} T4500"
    | "Samsung UE {диагональ} T4510"
    | "Samsung UE {диагональ} T5202"
    | "Samsung UE {диагональ} T5300"
    | "Samsung UE {диагональ} TU7002"
    | "Samsung UE {диагональ} TU7090"
    | "Samsung UE {диагональ} TU7097"
    | "Samsung UE {диагональ} TU7100"
    | "Samsung UE {диагональ} TU7140"
    | "Samsung UE {диагональ} TU7160"
    | "Samsung UE {диагональ} TU7170"
    | "Samsung UE {диагональ} TU7500"
    | "Samsung UE {диагональ} TU7540"
    | "Samsung UE {диагональ} TU7560"
    | "Samsung UE {диагональ} TU7570"
    | "Samsung UE {диагональ} TU8000"
    | "Samsung UE {диагональ} TU8300"
    | "Samsung UE {диагональ} TU8500"
    | "Samsung UE {диагональ} TU8510"
    | "Samsung UE {диагональ} TU8570"
    | "Sony KD {диагональ} X9005B"
    | "Sony KD {диагональ} XE7096"
    | "Sony KD {диагональ} XF7005"
    | "Sony KD {диагональ} XF7096"
    | "Sony KD {диагональ} XG7005"
    | "Sony KD {диагональ} XG7096"
    | "Sony KDL {диагональ} W605"
    | "Sony KDL {диагональ} W805A"
    | "Sony KDL {диагональ} W955"
    | "Sony KDL {диагональ} WD603"
    | "Sony KDL {диагональ} WD653"
    | "Sony KDL {диагональ} WD752"
    | "Sony KDL {диагональ} WD753"
    | "Sony KDL {диагональ} WD756"
    | "Sony KDL {диагональ} WE613"
    | "Sony KDL {диагональ} WE754"
    | "Sony KDL {диагональ} WE755"
    | "Sony KDL {диагональ} WF665"
    | "Sony KDL {диагональ} WF804"
    | "Sony KDL {диагональ} WF805"
    | "Sony KDL {диагональ} WG665"
    | "Toshiba {диагональ} L5780EC"
    | "Toshiba {диагональ} U5069"
    | "Toshiba {диагональ} U5855EC"


export type TVSubNames = 
    | "TV_Haier"
    | "TV_LG"
    | "TV_Panasonic"
    | "TV_Philips"
    | "TV_Samsung"
    | "TV_Sony"
    | "TV_Toshiba"

export type TVTypes = {
    id: number
    price: number
    name: TVNames
    subName: TVSubNames
    equipment: TVEquipment
    defects: TVDefects
}

export type TVEquipment = {
    powerCord: number
    remoteController: number
    originalBox: number
}

export type TVDefects = {
    scratchesBody: number
    scratchesFrame: number
    brokenButtons: number
    crackedChipScreen: number
    coloredWhiteDotsScreen: number
    scratchesDisplay: number
    doesntConnectWifi: number
    notCleatSound: number
    dontWorkSpeakers: number
    turnsOffItself: number
}